### ISSUE TITLE
Script fails on Manjaro Linux

### ISSUE THREAD

**Issue by MattMcHackit** [mrwnwttk/skillshare-dl#1]
```
$ python3 skillshare-dl_linux.py
Traceback (most recent call last):
  File "skillshare-dl_linux.py", line 255, in <module>
    main()
  File "skillshare-dl_linux.py", line 207, in main
    initializeChrome()
  File "skillshare-dl_linux.py", line 23, in initializeChrome
    server.start()
  File "/usr/lib/python3.7/site-packages/browsermobproxy/server.py", line 127, in start
    raise ProxyServerError("Can't connect to Browsermob-Proxy")
browsermobproxy.exceptions.ProxyServerError: Can't connect to Browsermob-Proxy
```

**Comment by Fabius716** [comment]
Did you try using superuser privileges? Like in ("sudo python3 setup_linux.py")

**Comment by mrwnwttk** [comment]
If the setup script is run with root it should be able to put all the binaries (for example browsermob-proxy) into the appropriate directories. Otherwise, you would have gotten quite a lot of error messages.

**Comment by victoralexander132** [comment]
I'm having the same issue in Ubuntu 19.04, I run the setup script with root privileges but get the following error in the skillshare-dl_linux.py script:

```
$ python3 skillshare-dl_linux.py
Traceback (most recent call last):
  File "skillshare-dl_linux.py", line 256, in <module>
    main()
  File "skillshare-dl_linux.py", line 208, in main
    initializeChrome()
  File "skillshare-dl_linux.py", line 23, in initializeChrome
    server.start()
  File "/usr/local/lib/python3.7/dist-packages/browsermobproxy/server.py", line 127, in start
    raise ProxyServerError("Can't connect to Browsermob-Proxy")
browsermobproxy.exceptions.ProxyServerError: Can't connect to Browsermob-Proxy
alexander@Satellite-S75-B:~/Downloads/skillshare-dl-master$ 
```
The output of the setup script is: 

```
------------skillshare-dl setup/installer------------
This script is going to install all the neccessary dependencies and tools needed to run skillshare-dl. Keep in mind:  This tool has only been tested on Linux using Chrome 77(at the time of writing) , so if you want to ensure that the script is working properly just set up a VM  with Ubuntu and Chrome.

Are you sure you want to proceed? [y/Y/n/N]: y
Are you using Linux? [y/Y/n/N]: y
The following tools are needed:
- Chrome/Chromium
- Python 3 (preferably 3.7)
- Selenium
- browsermob-proxy
- Chrome WebDriver
- pip/pip3
Is Chrome or Chromium installed and running the latest version? [y/Y/n/N]: y
Chrome already installed, skipping!
Installing Python 3...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.7.3-1).
0 upgraded, 0 newly installed, 0 to remove and 27 not upgraded.
Installing Selenium...
Requirement already satisfied: selenium in /usr/local/lib/python3.7/dist-packages (3.141.0)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from selenium) (1.24.1)
Installing browsermob-proxy...
Requirement already satisfied: browsermob-proxy in /usr/local/lib/python3.7/dist-packages (0.8.0)
Requirement already satisfied: requests>=2.9.1 in /usr/lib/python3/dist-packages (from browsermob-proxy) (2.21.0)
Downloading the browsermob-proxy binary...
mkdir: cannot create directory ‘/usr/local/bin/skillshare-dl/’: File exists
Moving it to /usr/local/bin/skillshare-dl/ ...
Downloading the ChromeDriver for Chrome 77...
unzip:  cannot find or open chromedriver_linux64.zip, chromedriver_linux64.zip.zip or chromedriver_linux64.zip.ZIP.
Moving it to /usr/bin/ ...
```

**Comment by mrwnwttk** [comment]
I updated the whole thing for Chrome 79, please try again.

**Comment by victoralexander132** [comment]
Thank you for the update, although I tried with a fresh installation of Ubuntu, only installing pip3 and chrome 79 and it didn't work. I get the same ProxyServer error.
```
sudo python3 setup_linux.py 
[sudo] password for raman: 
------------skillshare-dl setup/installer------------
This script is going to install all the neccessary dependencies and tools needed to run skillshare-dl. Keep in mind:
 This tool has only been tested on Linux using Chrome 79 (at the time of writing).

Are you sure you want to proceed? [y/n]: y
The following tools are needed:
- Chrome/Chromium
- Python 3 (preferably 3.7)
- Selenium
- browsermob-proxy
- Chrome WebDriver
- pip/pip3
Is Chrome or Chromium installed and running the latest version? [y/n]: y
Chrome already installed, skipping!
Installing Python 3...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.7.5-1).
y0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
Installing Selenium...
Requirement already satisfied: selenium in /usr/local/lib/python3.7/dist-packages (3.141.0)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from selenium) (1.24.1)
Installing browsermob-proxy...
Requirement already satisfied: browsermob-proxy in /usr/local/lib/python3.7/dist-packages (0.8.0)
Requirement already satisfied: requests>=2.9.1 in /usr/lib/python3/dist-packages (from browsermob-proxy) (2.21.0)
Setting permissions...
raman@Spectroscopy:~/Downloads/skillshare-dl-master$ python3 skillshare-dl_linux.py 
Traceback (most recent call last):
  File "skillshare-dl_linux.py", line 246, in <module>
    main()
  File "skillshare-dl_linux.py", line 198, in main
    initializeChrome()
  File "skillshare-dl_linux.py", line 18, in initializeChrome
    server.start()
  File "/usr/local/lib/python3.7/dist-packages/browsermobproxy/server.py", line 127, in start
    raise ProxyServerError("Can't connect to Browsermob-Proxy")
browsermobproxy.exceptions.ProxyServerError: Can't connect to Browsermob-Proxy
```

**Comment by mrwnwttk** [comment]
The only reason I can think of why it wouldn't work would be if java wasn't installed. 

`sudo apt-get install default-jre`

**Comment by victoralexander132** [comment]
> The only reason I can think of why it wouldn't work would be if java wasn't installed.
> 
> `sudo apt-get install default-jre`

Thanks a lot, that was it.

**Comment by mrwnwttk** [comment]
I'll add that to the setup script.
