### ISSUE TITLE
Errors when running skillshare-dl_windows.py with python 3.8

### ISSUE THREAD

**Issue by gguy825** [mrwnwttk/skillshare-dl#10]
When i run the windows file i get this after.

C:\Users\K\Desktop\skillshare-dl-master\skillshare-dl-master>py skillshare-dl_windows.py
Traceback (most recent call last):
  File "skillshare-dl_windows.py", line 7, in <module>
    from selenium import webdriver
  File "C:\Users\K\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\__init__.py", line 18, in <module>
    from .firefox.webdriver import WebDriver as Firefox  # noqa
  File "C:\Users\K\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 29, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
  File "C:\Users\K\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 26, in <module>
    from .webelement import WebElement
  File "C:\Users\K\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 43, in <module>
    getAttribute_js = pkgutil.get_data(_pkg, 'getAttribute.js').decode('utf8')
  File "C:\Users\K\AppData\Local\Programs\Python\Python38-32\lib\pkgutil.py", line 637, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\K\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\getAttribute.js'

**Comment by mrwnwttk** [comment]
This line is what baffles me the most:

`from .firefox.webdriver import WebDriver as Firefox`

I have no clue why it tries to use the Firefox Webdriver when I'm only importing selenium. This seems like an issue with selenium itself rather than with my script.

**Comment by gguy825** [comment]
Yea thats one thing that stood out to me also. I do have firefox installed but its not updated nor has it been used in the past few months if that matters. Chrome is also on the latest version as well.

**Comment by mrwnwttk** [comment]
The import already fails so there's not much I can do here. You'll have to figure this one out on your own.
