### ISSUE TITLE
I get an error when running the skillshare-dl_windows script

### ISSUE THREAD

**Issue by RedFox-ai** [mrwnwttk/skillshare-dl#15]
`[11788:3672:0126/150644.780:ERROR:cache_util_win.cc(21)] Unable to move the cache: Access is denied. (0x5)
[11788:3672:0126/150644.839:ERROR:cache_util.cc(141)] Unable to move cache folder C:\Users\Red Fox\AppData\Local\Google\Chrome\User Data\ShaderCache\GPUCache to C:\Users\Red Fox\AppData\Local\Google\Chrome\User Data\ShaderCache\old_GPUCache_000
[11788:3672:0126/150644.895:ERROR:disk_cache.cc(178)] Unable to create cache
[11788:3672:0126/150644.902:ERROR:shader_disk_cache.cc(605)] Shader Cache Creation failed: -2
[1892:10916:0126/150645.535:ERROR:broker_win.cc(55)] Error reading broker pipe: The pipe has been ended. (0x6D)
Opening in existing browser session.
Traceback (most recent call last):
  File ".\skillshare-dl_windows.py", line 263, in <module>
    main()
  File ".\skillshare-dl_windows.py", line 221, in main
    initializeChrome()
  File ".\skillshare-dl_windows.py", line 32, in initializeChrome
    driver = webdriver.Chrome(path_to_chromedriver, options = chrome_options)
  File "C:\Users\Red Fox\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Red Fox\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Red Fox\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Red Fox\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Red Fox\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir`

I would assume my system has no permission to create said cache, any idea how to fix it?

Thank you.

**Comment by RedFox-ai** [comment]
Nevermind, i got
