### ISSUE TITLE
Vpn Support

### ISSUE THREAD

**Issue by wickdick** [mrwnwttk/skillshare-dl#16]
I've been trying to use a VPN service (PIA) with this and it just won't work. Keeps sending back 
Title:
Title:
Title:
Title:
Title:
Title:
Title:
Title:
['', '', '', '', '', '', '', '']
1
//*[@id="video-region"]/div/div[2]/div[2]/div[1]/div[2]/div/div[2]/ul/li/ul/li[1]
Traceback (most recent call last):
  File "skillshare-dl_windows.py", line 262, in <module>
    main()
  File "skillshare-dl_windows.py", line 239, in main
    video_selector.click()
  File "C:\Users\David\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\David\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\David\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\David\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=77.0.3865.90)

When I turn off VPN it works fine. Fiddling with some of the settings gave me no new results. Do I need a VPN with this service, if so does it support it?

**Comment by mrwnwttk** [comment]
There's nothing I can do about this. Everything done related to VPNs is done server-side.
