### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by ckildau** [mrwnwttk/skillshare-dl#2]
Traceback (most recent call last):
  File "./skillshare-dl.py", line 41, in <module>
    r = requests.get(f"https://api.skillshare.com/classes/{id}", headers=headers)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1295, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib64/python3.6/http/client.py", line 1227, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 400: ordinal not in range(256)

Does anyone have the same issue?

**Comment by ckildau** [comment]
nevermind, wrong cookie used :/
